import { jsPDF } from "jspdf";
import { IntegrityScore, CarbonProject } from "@/types";
import { formatCredits } from "@/lib/scoreUtils";

export function generatePDFReport(
  project: CarbonProject,
  score: IntegrityScore
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(8, 11, 15);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(0, 229, 160);
  doc.setFontSize(24);
  doc.text("CarbonLens", 20, 25);
  doc.setFontSize(10);
  doc.setTextColor(136, 150, 165);
  doc.text("Carbon Credit Integrity Report", 20, 33);

  // Project Info
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(18);
  doc.text(project.name, 20, 55);

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Country: ${project.country}`, 20, 65);
  doc.text(`Type: ${project.projectType}`, 20, 72);
  doc.text(
    `Credits Issued: ${formatCredits(project.creditsIssued)} tonnes CO₂`,
    20,
    79
  );
  if (project.methodology) {
    doc.text(`Methodology: ${project.methodology}`, 20, 86);
  }

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 92, pageWidth - 20, 92);

  // Overall Score
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Integrity Analysis", 20, 105);

  doc.setFontSize(36);
  const scoreColor = getScoreRGB(score.overallScore);
  doc.setTextColor(scoreColor.r, scoreColor.g, scoreColor.b);
  doc.text(`${score.overallScore}`, pageWidth - 50, 105);
  doc.setFontSize(10);
  doc.text("/ 100", pageWidth - 30, 105);

  // Score Breakdown
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const scores = [
    { label: "Additionality", value: score.additionality },
    { label: "Permanence Risk", value: score.permanence },
    { label: "Leakage Risk", value: score.leakage },
    { label: "Community Impact", value: score.communityImpact },
  ];

  let y = 120;
  scores.forEach((s) => {
    doc.setTextColor(100, 100, 100);
    doc.text(s.label, 20, y);
    const c = getScoreRGB(s.value);
    doc.setTextColor(c.r, c.g, c.b);
    doc.text(`${s.value}/100`, pageWidth - 45, y);

    // Score bar
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(20, y + 2, pageWidth - 65, 4, 2, 2, "F");
    const barWidth = Math.max(1, ((pageWidth - 65) * s.value) / 100);
    if (s.value > 0) {
      doc.setFillColor(c.r, c.g, c.b);
      doc.roundedRect(20, y + 2, barWidth, 4, 2, 2, "F");
    }

    y += 18;
  });

  // Divider
  doc.line(20, y, pageWidth - 20, y);
  y += 12;

  // Red Flags
  if (score.redFlags.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(255, 107, 53);
    doc.text("Red Flags Detected", 20, y);
    y += 10;

    doc.setFontSize(10);
    score.redFlags.forEach((flag) => {
      doc.setTextColor(
        flag.severity === "HIGH" ? 255 : 245,
        flag.severity === "HIGH" ? 107 : 166,
        flag.severity === "HIGH" ? 53 : 35
      );
      doc.text(`[${flag.severity}]`, 20, y);
      doc.setTextColor(60, 60, 60);
      doc.text(flag.text, 48, y, { maxWidth: pageWidth - 70 });
      y += 12;
    });
  }

  // Summary
  y += 5;
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Summary", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const summaryLines = doc.splitTextToSize(score.summary, pageWidth - 40);
  doc.text(summaryLines, 20, y);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by CarbonLens · ${new Date().toLocaleDateString()}`,
    20,
    pageHeight - 10
  );
  doc.text(
    "Data: Verra VCS Registry · AI: Google Gemini",
    pageWidth - 85,
    pageHeight - 10
  );

  // Save
  const safeName = project.name.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`CarbonLens_${safeName}_report.pdf`);
}

function getScoreRGB(score: number): { r: number; g: number; b: number } {
  if (score < 40) return { r: 255, g: 107, b: 53 };
  if (score < 70) return { r: 245, g: 166, b: 35 };
  return { r: 0, g: 229, b: 160 };
}
